### ISSUE TITLE
Can't add a user that has a pending request on your myRequest list

### ISSUE THREAD

**Issue by kathleenlfp3** [CMPUT301F19T01/moodBook#158]
For example:
- user1 adds user2
- user2 then adds user1 ---> this gives an error message: "user already added"
But then...
- once user2 accepts user1's request, user2 can then add user1 as a friend.

**Comment by tylerelston** [comment]
by "user1 adds user2" do you mean user 1 sends a request to user 2?

I tried this case out but it behaves as expected.

User1 sent a request to User2
User2 sent a request to User1
User1 accepts User2
User2 accepts User1

**Comment by kathleenlfp3** [comment]
I think the error is, it's really not checking if the user that you are sending a request to is already in your Followings list, rather it is checking the ones under your Request list.

**Comment by tylerelston** [comment]
Hmm I took a look at the code and its checking if the user you're sending a request to is in your following (friend) list as expected already. Still unable to reproduce the bug
