### ISSUE TITLE
US 04.02.01 Search icon in wrong fragments

### ISSUE THREAD

**Issue by tylerelston** [CMPUT301F19T01/moodBook#52]
Search icon should be removed from all fragments except for the user's mood history

US 04.02.01	
"As a participant, I want to filter my mood history list to show only mood events with a 
particular emotional state."

**Comment by elisajdu** [comment]
Fixed code on MoodDB branch.
Solution: left each page fragment inherit from PageFragment class to ensure search menu option is removed at the beginning.
